name: ml_with_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yuris_cat_dog_classifier.tflite
    - assets/labels.txt